/* Generated by scriptc from C:/Users/dev/source/repos/tunecamp/sidecamp/apps/sidecamp-cli/test-scriptc.ts. Do not edit. */
#include "scr_runtime.h"
#include <math.h>
#include <stdio.h>
#include <stdlib.h>

static struct { size_t rc; size_t len; size_t cap; char data[9]; } sc_lit_0 =
    { SIZE_MAX, 8, 8, "Sidecamp" };
static struct { size_t rc; size_t len; size_t cap; char data[35]; } sc_lit_1 =
    { SIZE_MAX, 34, 34, "[Native Test] Ciao da scriptc per " };
static struct { size_t rc; size_t len; size_t cap; char data[2]; } sc_lit_2 =
    { SIZE_MAX, 1, 1, "!" };
static struct { size_t rc; size_t len; size_t cap; char data[26]; } sc_lit_3 =
    { SIZE_MAX, 25, 25, "[Native Test] Timestamp: " };

static ScrUnion sc_unit_0 = { .rc = SIZE_MAX, .tag = 1 }; /* u0 unit arm */

static ScrStr *sc_g_e_name; /* name */
static bool sc_g_e__x25_loaded; /* %loaded */

static void sc_f__x25_init_0(void);
static void sc_f__x25_main(void);
static ScrUnion * sc_f__x25_arr_idxOr_0(ScrArr *sc_l_a_0, double sc_l_i_0);

static bool sc_ut_0(ScrUnion *v); /* ToBoolean u0 */

static bool sc_ut_0(ScrUnion *v) { /* ToBoolean u0 */
  switch (v->tag) {
  case 0: return ((ScrStr *)scr_union_peek(v))->len != 0;
  case 1: return false;
  default: scr_trap("scriptc: internal error: invalid union tag\n");
  }
}


static void sc_f__x25_init_0(void) { /* C:/Users/dev/source/repos/tunecamp/sidecamp/apps/sidecamp-cli/test-scriptc.ts:1 */
  bool sc_t0 = sc_g_e__x25_loaded;
  if (sc_t0) {
    return; /* C:/Users/dev/source/repos/tunecamp/sidecamp/apps/sidecamp-cli/test-scriptc.ts:1 */
  }
  bool sc_t1 = true;
  sc_g_e__x25_loaded = sc_t1; /* C:/Users/dev/source/repos/tunecamp/sidecamp/apps/sidecamp-cli/test-scriptc.ts:1 */
  ScrArr *sc_t2 = scr_process_argv();
  double sc_t3 = 2.0;
  ScrUnion *sc_t4 = sc_f__x25_arr_idxOr_0(sc_t2, sc_t3);
  ScrStr *sc_t5;
  if (sc_ut_0(sc_t4)) {
    sc_t5 = scr_str_retain((ScrStr *)scr_union_peek(sc_t4));
    scr_union_release(sc_t4);
  } else {
    scr_union_release(sc_t4);
    ScrStr *sc_t6 = scr_str_retain((ScrStr *)&sc_lit_0);
    sc_t5 = sc_t6;
  }
  scr_str_release(sc_g_e_name);
  sc_g_e_name = sc_t5; /* C:/Users/dev/source/repos/tunecamp/sidecamp/apps/sidecamp-cli/test-scriptc.ts:1 */
  ScrStr *sc_t7 = scr_str_retain((ScrStr *)&sc_lit_1);
  ScrStr *sc_t8 = scr_str_retain(sc_g_e_name);
  ScrStr *sc_t9 = scr_str_concat(sc_t7, sc_t8);
  ScrStr *sc_t10 = scr_str_retain((ScrStr *)&sc_lit_2);
  ScrStr *sc_t11 = scr_str_concat(sc_t9, sc_t10);
  ScrLogArg sc_t12[1];
  sc_t12[0].tag = SCR_ARG_STR; sc_t12[0].v.s = sc_t11;
  scr_console_log(1, sc_t12); /* C:/Users/dev/source/repos/tunecamp/sidecamp/apps/sidecamp-cli/test-scriptc.ts:2 */
  scr_str_release(sc_t7);
  scr_str_release(sc_t8);
  scr_str_release(sc_t9);
  scr_str_release(sc_t10);
  scr_str_release(sc_t11);
  ScrStr *sc_t13 = scr_str_retain((ScrStr *)&sc_lit_3);
  double sc_t14 = scr_date_now();
  ScrStr *sc_t15 = scr_f64_to_scrstr(sc_t14);
  ScrStr *sc_t16 = scr_str_concat(sc_t13, sc_t15);
  ScrLogArg sc_t17[1];
  sc_t17[0].tag = SCR_ARG_STR; sc_t17[0].v.s = sc_t16;
  scr_console_log(1, sc_t17); /* C:/Users/dev/source/repos/tunecamp/sidecamp/apps/sidecamp-cli/test-scriptc.ts:3 */
  scr_str_release(sc_t13);
  scr_str_release(sc_t15);
  scr_str_release(sc_t16);
}

static void sc_f__x25_main(void) { /* C:/Users/dev/source/repos/tunecamp/sidecamp/apps/sidecamp-cli/test-scriptc.ts:1 */
  sc_f__x25_init_0(); /* C:/Users/dev/source/repos/tunecamp/sidecamp/apps/sidecamp-cli/test-scriptc.ts:1 */
}

static ScrUnion * sc_f__x25_arr_idxOr_0(ScrArr *sc_l_a_0, double sc_l_i_0) { /* C:/Users/dev/source/repos/tunecamp/sidecamp/apps/sidecamp-cli/test-scriptc.ts:1 */
  double sc_l_n_0; /* n */
  ScrStr *sc_l_v_0 = NULL; /* v */
  ScrArr *sc_t0 = scr_arr_retain(sc_l_a_0);
  double sc_t1 = scr_arr_len(sc_t0);
  sc_l_n_0 = sc_t1; /* C:/Users/dev/source/repos/tunecamp/sidecamp/apps/sidecamp-cli/test-scriptc.ts:1 */
  scr_arr_release(sc_t0);
  double sc_t2 = sc_l_i_0;
  double sc_t3 = sc_l_i_0;
  bool sc_t4 = sc_t2 != sc_t3;
  if (sc_t4) {
    ScrUnion *sc_t5 = (ScrUnion *)&sc_unit_0;
    scr_arr_release(sc_l_a_0);
    return sc_t5; /* C:/Users/dev/source/repos/tunecamp/sidecamp/apps/sidecamp-cli/test-scriptc.ts:1 */
  }
  double sc_t6 = sc_l_i_0;
  double sc_t7 = 0.0;
  bool sc_t8 = sc_t6 < sc_t7;
  if (sc_t8) {
    ScrUnion *sc_t9 = (ScrUnion *)&sc_unit_0;
    scr_arr_release(sc_l_a_0);
    return sc_t9; /* C:/Users/dev/source/repos/tunecamp/sidecamp/apps/sidecamp-cli/test-scriptc.ts:1 */
  }
  double sc_t10 = sc_l_i_0;
  double sc_t11 = sc_l_n_0;
  bool sc_t12 = sc_t10 >= sc_t11;
  if (sc_t12) {
    ScrUnion *sc_t13 = (ScrUnion *)&sc_unit_0;
    scr_arr_release(sc_l_a_0);
    return sc_t13; /* C:/Users/dev/source/repos/tunecamp/sidecamp/apps/sidecamp-cli/test-scriptc.ts:1 */
  }
  double sc_t14 = sc_l_i_0;
  double sc_t15 = floor(sc_t14);
  double sc_t16 = sc_l_i_0;
  bool sc_t17 = sc_t15 < sc_t16;
  if (sc_t17) {
    ScrUnion *sc_t18 = (ScrUnion *)&sc_unit_0;
    scr_arr_release(sc_l_a_0);
    return sc_t18; /* C:/Users/dev/source/repos/tunecamp/sidecamp/apps/sidecamp-cli/test-scriptc.ts:1 */
  }
  ScrArr *sc_t19 = scr_arr_retain(sc_l_a_0);
  double sc_t20 = sc_l_i_0;
  ScrStr *sc_t21 = scr_arr_get_ref(sc_t19, sc_t20);
  sc_l_v_0 = sc_t21; /* C:/Users/dev/source/repos/tunecamp/sidecamp/apps/sidecamp-cli/test-scriptc.ts:1 */
  scr_arr_release(sc_t19);
  ScrStr *sc_t22 = scr_str_retain(sc_l_v_0);
  ScrUnion *sc_t23 = scr_union_new_ref(0, sc_t22, &scr_str_retain_v, &scr_str_release_v, NULL);
  scr_arr_release(sc_l_a_0);
  scr_str_release(sc_l_v_0);
  return sc_t23; /* C:/Users/dev/source/repos/tunecamp/sidecamp/apps/sidecamp-cli/test-scriptc.ts:1 */
}

static void sc_release_globals(void) {
  scr_str_release(sc_g_e_name);
}

int main(int argc, char **argv) {
  scr_init();
  scr_error_vts[0].pre = 0; scr_error_vts[0].post = 4; /* Error */
  scr_error_vts[1].pre = 1; scr_error_vts[1].post = 1; /* TypeError */
  scr_error_vts[2].pre = 2; scr_error_vts[2].post = 2; /* RangeError */
  scr_error_vts[3].pre = 3; scr_error_vts[3].post = 3; /* SyntaxError */
  scr_error_vts[4].pre = 4; scr_error_vts[4].post = 4; /* DOMException */
  scr_lib_init(argc, argv);
  sc_f__x25_main();
  sc_release_globals();
  return 0;
}
