import { execSync } from 'node:child_process';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const crateDir = join(__dirname, '../crates/audio-wasm');
const wasmPath = join(crateDir, 'target/wasm32-unknown-unknown/release/audio_wasm.wasm');
const outDir = join(__dirname, '../src/wasm');
const outFile = join(outDir, 'wasmBinary.ts');

console.log('[build-wasm] Compiling Rust crate to wasm32-unknown-unknown...');
execSync('cargo build --target wasm32-unknown-unknown --release', { cwd: crateDir, stdio: 'inherit' });

const wasmBuffer = readFileSync(wasmPath);
const base64 = wasmBuffer.toString('base64');

mkdirSync(outDir, { recursive: true });
const tsContent = `// Auto-generated by scripts/build-wasm.js - DO NOT EDIT MANUALLY
export const WASM_BASE64 = "${base64}";

export function getWasmBytes(): Uint8Array {
  const binaryString = atob(WASM_BASE64);
  const bytes = new Uint8Array(binaryString.length);
  for (let i = 0; i < binaryString.length; i++) {
    bytes[i] = binaryString.charCodeAt(i);
  }
  return bytes;
}
`;

writeFileSync(outFile, tsContent, 'utf-8');
console.log(`[build-wasm] Generated ${outFile} (${(wasmBuffer.length / 1024).toFixed(1)} KB WASM)`);
